services:
  - type: web
    name: labexam1
    env: php
    buildCommand: |
      docker build -t labexam1 .
    runCommand: |
      php artisan config:cache && \
      php artisan route:cache && \
      php artisan view:cache && \
      php artisan migrate --force && \
      apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: labexam1
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgres
          name: labexam1-db
          property: connectionString.host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          type: postgres
          name: labexam1-db
          property: databaseName
      - key: DB_USERNAME
        fromService:
          type: postgres
          name: labexam1-db
          property: databaseUser
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: labexam1-db
          property: databasePassword
    autoDeploy: true
    plan: free
    numInstances: 1
    healthCheckPath: /

# PostgreSQL Database
postgres:
  - name: labexam1-db
    databaseName: labexam1
    user: labexam1_user
    plan: free
